config/routes.rb
Carouser::Application.routes.draw do
  resources :comments

  resources :events

  resources :users

  root :to => 'events#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :name, :event_id

  validates_presence_of :name, :within => 2..20, :message => "field can't be empty"
  validates_presence_of :body, :message => "field can't be empty"

  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :event, :title, :address, :date, :start_time, :end_time, :description, :where, :host_id, :ip_address, :latitude, :longitude

  has_many :reservations
  belongs_to :host, :class_name => "User" ,:foreign_key => "host_id"
  has_many :comments, :dependent => :destroy

  validates :address, :presence => :true
  ##validates_presence	

  geocoded_by :address
  after_validation :geocode


end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :event_id, :user_id

  belongs_to :user
  belongs_to :event
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  attr_accessible :age, :host, :interests, :name, :salt, :hashed_password, :password, :password_confirmation

  has_many :reservations
  has_many :hosted_events, :class_name=> 'Event', :foreign_key => 'host_id'
  has_many :attended_events, :class_name=> 'Event', :through => :reservations

  belongs_to :host, :class_name => 'User', :foreign_key => 'host_id'

  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true #automatically checking passwords mathc, will need to add second form for this though
  attr_accessor :password_confirmation
  	# Making password a virtual attribute of the model, won't be persisted to database.
  attr_reader :password 	
  validate :password_must_be_present

  def User.authenticate(name, password)
  	if user = find_by_name(name)
  		if user.hashed_password == encrypt_password(password, user.salt)
  			user
  		end
  	end
  end

  private
  
	  def password_must_be_present
	  	errors.add(:password, "Missing Password") unless hashed_password.present?
	  end

	  
	  def User.encrypt_password(password, salt) 
	  	#The hexdigest part, and several other similar methods are written 
	  	#as a C extension for speed. #It's found in ext/digest/ in the #
	  	#Ruby source.
	  	Digest::SHA2.hexdigest(password + "wibble" + salt)
		end

		def generate_salt
			self.salt = self.object_id.to_s + rand.to_s
		end

		def password=(password)
			@password = password

			if password.present?
				generate_salt  	
				self.hashed_password = self.class.encrpyt_password(password,salt)
			end
		end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create

    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save

        format.html { redirect_to @comment.event, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        # @event = Event.find(params[:comment][:event_id])
        @event = @comment.event
        format.html { render "events/show" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show

    @event = Event.find(params[:id])
    @comment = Comment.new(:event_id => @event.id )

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create

    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        # Chaned redirect from @user to users_url
        format.html { redirect_to(users_url, :notice => "User #{@user.name} was successfully created.") }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_url, :notice => "User #{@user.name} was successfully updated.") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% @event.comments.each do |comment| %> 

	<div class="comment">
		<b><%=h comment.name %> says:</b><br>
		<%= simple_format h(comment.body) %>
	</div>
<% end %> 

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Body</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.body %></td>
    <td><%= comment.event_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Event:</b>
  <%= @comment.event_id %>
</p>



<%= link_to 'Back', comments_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.time_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :where %><br />
    <%= f.text_field :where %>
  </div>

  <%= f.hidden_field :longitude %> 
  <%= f.hidden_field :latitude %> 

  <div class="actions" id="glow">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<head>

  <link href="/stylesheets/main.css" media="screen" rel="stylesheet" type="text/css" />
  <image style= "opacity = .1">
  <script type="text/javascript" src="/javascripts/jQuery"></script>
    
</head>


<body>
<div id="container">
    <h1>Carouser</h1>
    
    <h3>Happy Hours and Events Near You</h3>

    <table >
      <tr>
        <th>Title</th>
        <th>Where</th>
        <th>Date</th>
        <th> When </th>
        <th>Distance To Event</th>

        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @events.each do |event| %>
        <% distance = event.distance_to(request.ip).to_i %>  
      <tr>
        <td><%= link_to event.title, event %></td>
        <td><%= event.where %></td>
        <td><%= event.date.strftime("%A, %B %e"    ) %></td>
        <td>From<%=event.start_time.strftime("%l:%M %p")%> To <%=event.end_time.to_s(:time) %></td>
        <td><%= number_with_precision(distance, :precision => 0) %> meters</td>

        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>
    <br> <br>


    <%= link_to 'Create a new Event!', new_event_path, :confirm => "Are you sure?" %>
</div>
</body>

app/views/events/new.html.erb
<div id="container">
	<h1>New event</h1>

	<%= render 'form' %>

	<%= link_to 'Back', events_path %>
</div>

app/views/events/show.html.erb
<html>
<head>
  <%= stylesheet_link_tag "main" %>
</head>


<body>
  <div id="container">

    <p id="notice"><%= notice %></p>
      
    <h1>
      <%= @event.title %> @ <%=@event.where %>
    </h1>

    <div id="left" >
      <p>
        <%= link_to @event.address, "http://maps.google.com/?q=#{@event.latitude},#{@event.longitude}", {:target => "_new"} %>
      </p>

      <p>
        <%= @event.date.to_s(:date) %>
      </p>

      <p>
        From <%= @event.start_time.to_s(:time) %> to  <%= @event.end_time.to_s(:time) %>
      </p>

      <p>
        About this event
        <br>
        <%= @event.description %>
      </p> 
    </div> 

    <div id="right">
      <%= render '/comments/comment', :collection => @event.comments %>
    </div>

  <!--   <p>
    <%= link_to "Map", "http://maps.google.com/?q=#{@event.latitude},#{@event.longitude}", {:target => "_new"} %>
    </p> -->

    <p id="image">
      <%= image_tag("http://maps.googleapis.com/maps/api/streetview?size=600x300&location=#{@event.latitude}, #{@event.longitude}&sensor=false") %>
    </p id="image">


    <%= form_for @comment do |f| %>

      <%= f.hidden_field :event_id %>

      <p>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
      </p>

      <p>
        <%= f.label :body %><br />
        <%= f.text_area :body %>
      </p>
     
      <p>
        <%= f.submit "Post Comment" %>
      </p>
    <% end %>

    <% if @comment.errors  %>
      <% @comment.errors.full_messages.each do |error| %>
        <ul><%= error %></ul>
      <% end %>
    <% end %>



    <%= link_to 'Edit', edit_event_path(@event) %> |
    <%= link_to 'Back', events_path %>
</div>
</body>
</html> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carouser</title>
  <%= stylesheet_link_tag  "main", :media => "all" %>
</head>

<body>
<div id="wrapper">
	<div id="header">
		<div id="nav"><%= link_to "Home", events_path %> | <a href="#">About</a> | <a href="#">Contact</a> | <a href="#">My Events</a>
					  | <%= link_to "Users", users_path%></div>
		<div id="bg"></div>
	</div>

	<%= yield %>

	<div id="footer">
		Copyright &copy; 2013 Apollo Creed. All rights reserved.<br/>
		Happy Hour Responsibly</a>.
	</div>
</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend> Enter User Details</legend>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => 40 %>
  </div>

  <div class="field">
    <%= f.label :password, 'Password' %><br />
    <%= f.password_field :password, :size => 40 %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, :size => 40 %>
  </div>

  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :interests %><br />
    <%= f.text_area :interests %>
  </div>
  <div class="field">
    <%= f.label :host %><br />
    <%= f.check_box :host %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Interests</th>
    <th>Host</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.age %></td>
    <td><%= user.interests %></td>
    <td><%= user.host %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Age:</b>
  <%= @user.age %>
</p>

<p>
  <b>Interests:</b>
  <%= @user.interests %>
</p>

<p>
  <b>Host:</b>
  <%= @user.host %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>